### ISSUE TITLE
Incorporate full documentation into a solution

### ISSUE THREAD

**Issue by garzarobm** [Quicksilver466/FCCGAN_pytorch#1]
Need help in working on a possible solution for a current project of mine that uses GANs projected for completion in the far future. Would love hearing about more details, I reached out through discord as Robjects, I figure you could be interested in helping out. Feel free to reach out or just delete the messages and/or issue if disinterested.

**Comment by Quicksilver466** [comment]
Hey hi, I am afraid I am having a pretty low bandwidth currently, but I would love to know anything about the project as long as it's disclosable.

Also I would also like if we can keep in touch with respect to the developments in ML space and projects/idea sharing.

**Comment by garzarobm** [comment]
Absolutely, please message me at robjects@protonmail.com and lets exchange contact info. 😀

**Comment by Quicksilver466** [comment]
Sure, I will contact you through mail, sorry it took me this long, I was sick and even my laptop had an issue.

**Comment by garzarobm** [comment]
No problem at all! Take your time!

**Comment by Quicksilver466** [comment]
Hi Mike,

Let's just connect over discord once.

Let me know when you will be available.
We will connect by adjusting over timezone. I fall in IST so let me know a
suitable time.

Regards,
Shaunak Ketkar

**Comment by garzarobm** [comment]
Contacted!
